# DAQ settings
mmconfigfile: "C:/Users/plexus/Desktop/kinetix-DemoStage-mm.cfg"
DAQ:
  device_name: 'Dev1'
  VC_ao_channel: 'ao0'
  exttrig_counter: 'ctr0'
  exttrig_counter_channel: 'PFI12'
  sampling_rate: 10000.
  aotf_laser_dos:
    "488": "port0/line2"
    "561": "port0/line3"
    "595": "port0/line4"
    "640": "port0/line5"
    "775": "port0/line6"
  aotf_blanking_do: "port1/line1"

camera:
  exposure_time: 1.22 
  trigger_mode: 'Edge Trigger'
  pvcam_port: "Dynamic Range"
  scan_width: 4
  scan_direction: 'Up'
  pixel_type: '16bit'
  pixel_size_um: 6.5

voice_coil:
  mirror_neutral_voltage: 0.0
  calibration_path: "C:/Users/plexus/Documents/pymmcore-plus-panASLM/Functions/voice_coil_calibration.csv"

xyz_stages:
  device_name: 'PI V-508 L-306'
  needs_commutation: True
  x_limit_min: -5.0
  x_limit_max: 5.0
  y_limit_min: -5.0
  y_limit_max: 5.0
  z_limit_min: 0.
  z_limit_max: 12.
  x_home: -20.0
  y_home: 6.0
  z_home: 0.0